like_icon: 
  default: far-heart
  description: 
    en: "icon displayed before likes count"
    zh_CN: "显示在喜欢数前面的图标"
  type: string
allow_user_setting: 
  default: false
  description: 
    en: "use user perference to override default setting"
    zh_CN: "由用户选择是否显示赞"
  type: bool
user_field:
  default: user_field_1
  description: 
    en: "user field name to get user setting"
    zh_CN: "用于用户自定义的用户字段名称"
  type: string
display_like_count: 
  default: false
  description: 
    en: "display like count"
    zh_CN: "显示喜欢的数量"
  type: bool
display_reply_count: 
  default: true
  description: 
    en: "display reply count"
    zh_CN: "显示回复的数量"
  type: bool
reply_icon: 
  default: far-comment-alt
  description: 
    en: "icon displayed before replies count"
    zh_CN: "显示在回复数前面的图标"
  type: string
svg_icons: 
  default: far-comment-alt
  description: 
    en: "include extra font-awesome icon name you want to use"
    zh_CN: "输入想用于图标的所有非默认font-awesome图标名称"
  list_type: compact
  type: list
