like_icon: 
  default: far-heart
  description: 
    en: "icon displayed before likes count"
    zh_CN: "显示在喜欢数前面的图标"
  type: string
reply_icon: 
  default: far-comment-alt
  description: 
    en: "icon displayed before replies count"
    zh_CN: "显示在回复数前面的图标"
  type: string
svg_icons: 
  default: far-comment-alt
  description: 
    en: "include extra font-awesome icon name you want to use"
    zh_CN: "输入想用于图标的所有非默认font-awesome图标名称"
  list_type: compact
  type: list
